language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PdkC8BBc1bHasdaCcLbkqntcShVAw/EQsJzkUnA+Yg8a6NrW3ETaalYUUSOk+0DYitOf7UoyQsZ1ZFBZkc/uPJHQPzi9jCvcKHEW1CcGMILp60pXgfpdpF0qh97Uqd02mTKokvaQSxe2DvNlwjFkAshx+3FsYadd93Sn1wy4PumtoFC9ETP5JjDD1QOSH1IyMIFDHF4S6t6zXyizfeihQ/+WQuFynSfr2khKDzYNVqXTSz8n+SdRJ8hNDJotuoW8pcP90Jsj10VOz9xTMbxIKau6QmnU1fAXQNXz74349AoDK+1o120M8S9RArTcQQQIeRTPY3Ztzmwxmt1brasf9t0utNoWZk6P7WyUSzltZntbUrmfqF4ZLGIBtSOG4TTOBH3Ob86nNxGWaS1JDNsYB1VEL14Sf3LPCaRVlEB5heUeIY7nURcOmpw98fffhfPaNRdJEpNzrzNp2mqP/uz8o3HNEs8umA7K/jxT2jqViqMnU175yM24QXuDugQpBUCB4r035I5oHceAqZ60K+QdFWjKJVYi8NMtp/LsiMiaUmUXjUR+zXs4RzE+B+QHj02HOC+Zl6EU1D1LNYzsKNmBb/1jiSRjbny9i1NmJ9uEtbmiepBnCzRHblsy0WA3LTLMetTm49MdMr75860CIDdCdUMys8MS/iNVwWzci9YIVGk=
  file:
    - 'mdast-util-definitions.js'
    - 'mdast-util-definitions.min.js'
  on:
    tags: true
